"""initial schema

Revision ID: 07517be42f00
Revises: 
Create Date: 2026-09-06 11:27:22.177710
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '07517be42f00'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('faculty', 'admin', name='app_role', native_enum=False, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('program_outcomes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('courses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('term', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(code) BETWEEN 2 AND 20', name='ck_courses_code_len'),
    sa.ForeignKeyConstraint(['owner_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index('ix_courses_owner_active', ['owner_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
        batch_op.create_index('uq_courses_owner_code_active', ['owner_id', 'code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))

    op.create_table('artefacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('syllabus', 'question_paper', 'marks_sheet', 'rubric', 'answer_set', name='artefact_kind', native_enum=False, length=32), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.Column('term', sa.Text(), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('mime', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('lang', sa.Enum('en', 'bn', 'mixed', 'unknown', name='text_lang', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'extracting', 'done', 'failed', name='extraction_status', native_enum=False, length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('declared_total_marks', sa.Numeric(precision=6, scale=2, asdecimal=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(storage_path IS NOT NULL) OR (extracted_text IS NOT NULL)', name='ck_artefacts_source'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artefacts', schema=None) as batch_op:
        batch_op.create_index('ix_artefacts_course_kind_status', ['course_id', 'kind', 'status'], unique=False)

    op.create_table('course_outcomes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('bloom_level', sa.Enum('remember', 'understand', 'apply', 'analyze', 'evaluate', 'create', name='bloom_level', native_enum=False, length=32), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2, asdecimal=False), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('weight > 0', name='ck_course_outcomes_weight'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'code', name='uq_course_outcomes_course_code')
    )
    with op.batch_alter_table('course_outcomes', schema=None) as batch_op:
        batch_op.create_index('ix_course_outcomes_course', ['course_id'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('module', sa.Enum('exam_audit', 'attainment', 'syllabus_check', 'calibration', name='run_module', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('queued', 'analyzing', 'completed', 'partial', 'failed', name='run_status', native_enum=False, length=32), nullable=False),
    sa.Column('progress_pct', sa.SmallInteger(), nullable=False),
    sa.Column('current_stage', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('inputs', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('context_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('prompt_versions', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('progress_pct BETWEEN 0 AND 100', name='ck_runs_progress'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index('ix_runs_course_created', ['course_id', 'created_at'], unique=False)
        batch_op.create_index('ix_runs_owner_status', ['owner_id', 'status'], unique=False)
        batch_op.create_index('uq_runs_owner_idempotency', ['owner_id', 'idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'), sqlite_where=sa.text('idempotency_key IS NOT NULL'))

    op.create_table('topics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source_artefact_id', sa.Uuid(), nullable=True),
    sa.Column('embedding', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('embedding_model', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_artefact_id'], ['artefacts.id'], name='fk_topics_source_artefact', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'code', name='uq_topics_course_code')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index('ix_topics_course', ['course_id'], unique=False)

    op.create_table('co_po_map',
    sa.Column('co_id', sa.Uuid(), nullable=False),
    sa.Column('po_id', sa.Uuid(), nullable=False),
    sa.Column('strength', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('strength BETWEEN 0 AND 3', name='ck_co_po_map_strength'),
    sa.ForeignKeyConstraint(['co_id'], ['course_outcomes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['po_id'], ['program_outcomes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('co_id', 'po_id', name='pk_co_po_map')
    )
    op.create_table('findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('coverage_gap', 'overweight', 'bloom_imbalance', 'duplicate', 'fairness', 'marks_total_mismatch', 'untagged_question', 'suggestion', 'co_underperformance', 'po_underperformance', 'action', 'overlap', 'prerequisite_gap', 'missing_topic', 'repositioning', 'divergence', 'prescore_note', 'rubric_clarification', name='finding_type', native_enum=False, length=32), nullable=False),
    sa.Column('severity', sa.Enum('info', 'low', 'medium', 'high', name='finding_severity', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('evidence_snippet', sa.Text(), nullable=True),
    sa.Column('target_kind', sa.Enum('question', 'course_outcome', 'program_outcome', 'topic', 'answer', 'criterion', 'course', 'none', name='target_kind', native_enum=False, length=32), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('target_label', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('provenance', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.Enum('open', 'accepted', 'dismissed', name='finding_status', native_enum=False, length=32), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(status = 'open' AND decided_by IS NULL) OR (status <> 'open' AND decided_by IS NOT NULL)", name='ck_findings_decided'),
    sa.ForeignKeyConstraint(['decided_by'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index('ix_findings_owner_status', ['owner_id', 'status'], unique=False)
        batch_op.create_index('ix_findings_run_created', ['run_id', 'created_at'], unique=False)
        batch_op.create_index('ix_findings_run_type_label', ['run_id', 'type', 'target_label'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('artefact_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('marks', sa.Numeric(precision=6, scale=2, asdecimal=False), nullable=False),
    sa.Column('bloom_level', sa.Enum('remember', 'understand', 'apply', 'analyze', 'evaluate', 'create', name='bloom_level', native_enum=False, length=32), nullable=True),
    sa.Column('bloom_source', sa.Enum('ai', 'faculty', name='map_source', native_enum=False, length=32), nullable=True),
    sa.Column('embedding', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('embedding_model', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('marks >= 0', name='ck_questions_marks'),
    sa.ForeignKeyConstraint(['artefact_id'], ['artefacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artefact_id', 'number', name='uq_questions_artefact_number')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index('ix_questions_artefact_order', ['artefact_id', 'sort_order'], unique=False)

    op.create_table('run_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('pct', sa.SmallInteger(), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('pct IS NULL OR (pct BETWEEN 0 AND 100)', name='ck_run_events_pct'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'seq', name='uq_run_events_run_seq')
    )
    op.create_table('run_inputs',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('artefact_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.CheckConstraint("role IN ('draft','past','marks','paper','syllabus','rubric','answer_set')", name='ck_run_inputs_role'),
    sa.ForeignKeyConstraint(['artefact_id'], ['artefacts.id'], name='fk_run_inputs_artefact_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'artefact_id', 'role', name='pk_run_inputs')
    )
    with op.batch_alter_table('run_inputs', schema=None) as batch_op:
        batch_op.create_index('ix_run_inputs_artefact', ['artefact_id'], unique=False)

    op.create_table('usage_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('purpose', sa.Enum('extraction', 'exam_audit', 'attainment', 'syllabus_check', 'calibration', 'suggestion', 'embedding', name='usage_purpose', native_enum=False, length=32), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6, asdecimal=False), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('ok','retry','failed')", name='ck_usage_logs_status'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.create_index('ix_usage_logs_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('question_co_map',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('co_id', sa.Uuid(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3, asdecimal=False), nullable=True),
    sa.Column('source', sa.Enum('ai', 'faculty', name='map_source', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name='ck_question_co_map_confidence'),
    sa.ForeignKeyConstraint(['co_id'], ['course_outcomes.id'], name='fk_question_co_map_co_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'co_id', name='pk_question_co_map')
    )
    with op.batch_alter_table('question_co_map', schema=None) as batch_op:
        batch_op.create_index('ix_question_co_map_co', ['co_id'], unique=False)

    op.create_table('question_topic_map',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3, asdecimal=False), nullable=True),
    sa.Column('source', sa.Enum('ai', 'faculty', name='map_source', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'topic_id', name='pk_question_topic_map')
    )
    with op.batch_alter_table('question_topic_map', schema=None) as batch_op:
        batch_op.create_index('ix_question_topic_map_topic', ['topic_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_topic_map', schema=None) as batch_op:
        batch_op.drop_index('ix_question_topic_map_topic')

    op.drop_table('question_topic_map')
    with op.batch_alter_table('question_co_map', schema=None) as batch_op:
        batch_op.drop_index('ix_question_co_map_co')

    op.drop_table('question_co_map')
    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_usage_logs_user_created')

    op.drop_table('usage_logs')
    with op.batch_alter_table('run_inputs', schema=None) as batch_op:
        batch_op.drop_index('ix_run_inputs_artefact')

    op.drop_table('run_inputs')
    op.drop_table('run_events')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index('ix_questions_artefact_order')

    op.drop_table('questions')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index('ix_findings_run_type_label')
        batch_op.drop_index('ix_findings_run_created')
        batch_op.drop_index('ix_findings_owner_status')

    op.drop_table('findings')
    op.drop_table('co_po_map')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index('ix_topics_course')

    op.drop_table('topics')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index('uq_runs_owner_idempotency', postgresql_where=sa.text('idempotency_key IS NOT NULL'), sqlite_where=sa.text('idempotency_key IS NOT NULL'))
        batch_op.drop_index('ix_runs_owner_status')
        batch_op.drop_index('ix_runs_course_created')

    op.drop_table('runs')
    with op.batch_alter_table('course_outcomes', schema=None) as batch_op:
        batch_op.drop_index('ix_course_outcomes_course')

    op.drop_table('course_outcomes')
    with op.batch_alter_table('artefacts', schema=None) as batch_op:
        batch_op.drop_index('ix_artefacts_course_kind_status')

    op.drop_table('artefacts')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index('uq_courses_owner_code_active', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index('ix_courses_owner_active', postgresql_where=sa.text('deleted_at IS NULL'))

    op.drop_table('courses')
    op.drop_table('program_outcomes')
    op.drop_table('profiles')
    # ### end Alembic commands ###
